{
  imports = [
    ./hardware-configuration.nix
    ./selfhosted/ai.nix
    ./selfhosted/audiobookshelf.nix
    ./selfhosted/freshrss.nix
    ./selfhosted/home-assistant.nix
    ./selfhosted/invidious.nix
    ./selfhosted/jellyfin.nix
    ./selfhosted/nix-serve.nix
    ./selfhosted/sunshine.nix
    ./selfhosted/syncthing.nix
    ./selfhosted/vscode-server.nix
    ./gamescope-session.nix
    ./nvidia.nix
    ./rgb.nix
    ./virtualization.nix
    ./wake-on-lan.nix
    ./../../modules/core
  ];
}
