{
  imports = [
    ./scripts/scripts.nix
    ./discord.nix
    ./firefox.nix
    ./foot.nix
    ./git.nix
    ./gtk.nix
    ./mako.nix
    ./mangohud.nix
    ./mpv.nix
    ./packages.nix
    ./pointer-cursor.nix
    ./sway.nix
    ./vscode.nix
    ./waybar.nix
    ./zsh.nix
  ];
}
