{
  imports = [
    ./programs/flatpak.nix
    ./programs/obs.nix
    ./programs/steam.nix
    ./programs/thunar.nix
    ./programs/virt-manager.nix
    ./programs/zsh.nix
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./fonts.nix
    ./iphone.nix
    ./user.nix
    ./libinput.nix
    ./networking.nix
    ./services.nix
    ./system.nix
    ./user.nix
  ];
}
